In [1]:
from quantum_dataset import QM7, QM7b, QM7X, QM9, ANI1x, Champs, SuperSet
from quantum_learning import Learn, Selector, ChampSelector
from quantum_model import FFNet, SetTransformer
from torch.optim import Adam
from torch.nn import MSELoss, L1Loss

In [ ]:
opt_params = {'lr': 0.001}
model_params = {'D_in': 23*23, 
                'H': 4096, 
                'D_out': 1, 
                'model_name': 'funnel'}
ds_params = {}
crit_params = {'reduction': 'sum'}

Learn(Dataset=QM7, Model=FFNet, Sampler=Selector, Optimizer=Adam, Criterion=L1Loss, 
      batch_size=256, epochs=10, opt_params=opt_params, model_params=model_params, 
      ds_params=ds_params, crit_params=crit_params, save_model=False, load_model=False)

In [ ]:
opt_params = {'lr': 0.001}
model_params = {'D_in': 23*23+13, 
                'H': 4096, 
                'D_out': 1, 
                'model_name': 'funnel'}
ds_params = {'target': 'E', 
             'features': ['alpha_p','alpha_s','HOMO_g','HOMO_p','HOMO_z','LUMO_g',
                          'LUMO_p','LUMO_z','IP','EA','E1','Emax','Imax']}
crit_params = {'reduction': 'sum'}

Learn(Dataset=QM7b, Model=FFNet, Sampler=Selector, Optimizer=Adam, Criterion=L1Loss, 
      batch_size=256, epochs=10, opt_params=opt_params, model_params=model_params, 
      ds_params=ds_params, crit_params=crit_params, save_model=False, load_model=False)

In [ ]:
opt_params = {'lr': 0.001}
model_params = {'D_in': 10*10, 
                'H': 2048, 
                'D_out': 1, 
                'model_name': 'funnel'}
ds_params = {'n': 133885, 
             'features': ['coulomb'], 
             'target': 'U0',
             'pad': 10, 
             'filter_on': ('n_atoms','>','10'),
             'use_pickle': False}
crit_params = {'reduction': 'sum'}

Learn(Dataset=QM9, Model=FFNet, Sampler=Selector, Optimizer=Adam, Criterion=L1Loss,
      batch_size=4, epochs=10, model_params=model_params, ds_params=ds_params, 
      opt_params=opt_params, crit_params=crit_params, save_model=False, load_model=False)

In [ ]:
opt_params = {'lr': 0.001}
model_params = {'D_in': 128+63+63+63, 
                'H': 2048, 
                'D_out': 1, 
                'model_name': 'funnel'}
ds_params = {'features': ['atomic_numbers','coordinates'],
             'targets': ['wb97x_dz.energy'], 
             'pad': 189,
             'criterion': 'wb97x_dz.energy',
             'conformation': 'random',
             'in_file': './data/ani1/ani1x-release.h5'}
crit_params = {'reduction': 'sum'}

Learn(Dataset=ANI1x, Model=FFNet, Sampler=Selector, Optimizer=Adam, Criterion=L1Loss, 
      batch_size=256, epochs=100, opt_params=opt_params, model_params=model_params, 
      ds_params=ds_params, crit_params=crit_params, save_model=False, load_model=False)

In [ ]:
opt_params = {'lr': 0.001}
model_params = {'D_in': 128+32+64+32+64, 
                'H': 2048, 
                'D_out': 1, 
                'model_name': 'funnel'}
ds_params = {'n': 4658146, 
             'features': False,
             'use_h5': False,  
             'infer': False}
crit_params = {'reduction': 'sum'}
sample_params = {'split': .1, 'subset': False}

Learn(Dataset=Champs, Model=FFNet, Sampler=ChampSelector, Optimizer=Adam, Criterion=L1Loss,
      batch_size=1024, epochs=10, model_params=model_params, ds_params=ds_params, 
      sample_params=sample_params, opt_params=opt_params, crit_params=crit_params, 
      save_model=True, load_model=False)

In [ ]:
model_params = {'D_in': 128+32+64+32+64, 
                'H': 2048, 
                'D_out': 1, 
                'model_name': 'funnel'}
ds_params = {'features': False,
             'use_h5': False,  
             'infer': True}

Learn(Dataset=Champs, Model=FFNet, Sampler=Selector, batch_size=2048, model_params=model_params, 
      ds_params=ds_params, load_model='./models/20201021_2101.pth', adapt=False)

In [ ]:
ds_params = {'features': 
                 ['DIP','HLgap','KSE','atC6','atNUM','atPOL','atXYZ', 
                 'eC','eDFTB+MBD','eEE','eH','eKIN','eKSE','eL','eMBD',
                 'eNE','eNN','ePBE0','ePBE0+MBD','eTS','eX','eXC','eXX',
                 'hCHG','hDIP','hRAT','hVDIP','hVOL','mC6','mPOL','mTPOL',
                 'pbe0FOR','sMIT','sRMSD','totFOR','vDIP','vEQ','vIQ',
                 'vTQ','vdwFOR','vdwR'],
             'pad': 1024,
             'target': ['eAT'],
             'selector': ['i1-c1-opt']}

opt_params = {'lr': 0.001}

model_params = {'D_in': 1024, 
                'H': 2048, 
                'D_out': 1, 
                'model_name': 'funnel'}

crit_params = {'reduction': 'sum'}

sample_params = {'split': .1, 'subset': False}

Learn(Dataset=QM7X, Model=FFNet, Sampler=Selector, Optimizer=Adam, Criterion=L1Loss,
      batch_size=256, epochs=10, model_params=model_params, ds_params=ds_params, 
      sample_params=sample_params, opt_params=opt_params, crit_params=crit_params, 
      save_model=False, load_model=False)

In [ ]:
ds_params = {'n': 133885, 
             'features': ['coulomb'], 
             'target': 'U0',
             'pad': 10, 
             'filter_on': ('n_atoms','>','10'),
             'use_pickle': 'qm9_n_atoms_10_or_less.p'}

opt_params = {'lr': 0.001}

model_params = {'dim_input': 100,
                'num_outputs': 1,
                'dim_output': 1,
                'num_inds': 32,
                'dim_hidden': 128,
                'num_heads': 4,
                'ln': False}

crit_params = {'reduction': 'sum'}

sample_params = {'split': .1, 'subset': False}

Learn(Dataset=QM9, Model=SetTransformer, Sampler=Selector, Optimizer=Adam, Criterion=L1Loss,
      batch_size=4, epochs=2, model_params=model_params, ds_params=ds_params, 
      sample_params=sample_params, opt_params=opt_params, crit_params=crit_params, 
      save_model=False, load_model=False)

In [6]:
ds_params = {'features': ['hf_tz.energy'],
             'targets': ['wb97x_dz.energy'], 
             'pad': False,
             'criterion': 'wb97x_dz.energy',
             'conformation': 'min',
             'in_file': './data/ani1/ani1x-release.h5'}

ani1x = ANI1x(**ds_params)

In [7]:
len(ani1x.ds_idx)

21

In [8]:
lg = 0
for mol in ani1x.ds_idx:
    val = ani1x[mol]
    sz = val[0].shape[0]
    if sz > lg:
        lg = sz
print(lg)

1


In [9]:
ani1x.ds_idx

['C1H4N4O4',
 'C1H5N3O5',
 'C2H10N4O3',
 'C2H10N6O1',
 'C2H11N5O1',
 'C2H5N1O5',
 'C3H13N3',
 'C3H2N4O3',
 'C3H4N6O1',
 'C3H6N8O3',
 'C4H3N3O4',
 'C4H4N8',
 'C6H17N1',
 'C6H1N3O3',
 'C6H2N2O3',
 'C6H2N6',
 'C7H1N3',
 'C9H2N2O1',
 'C9H3N1O2',
 'C9H4O3',
 'H4N4O1']

In [10]:
ani1x['C6H2N2O3']

(tensor([-561.9130]), tensor([]), tensor([-564.6920], dtype=torch.float64))

In [24]:
ds_params = {'features': ['coordinates', 'atomic_numbers'],
             'targets': ['ccsd(t)_cbs.energy'], 
             'pad': 64,
             'criterion': 'ccsd(t)_cbs.energy',
             'conformation': 'min',
             'in_file': './data/ani1/ani1x-release.h5'}

ani1x = ANI1x(**ds_params)

#find the length of the longest molecule
#lg = 0
#for mol in ani1x.ds_idx:
#    val = ani1x[mol]
#    sz = val[0].shape[0]
#    if sz > lg:
#        lg = sz
#print(lg)

In [25]:
len(ani1x.ds_idx)

21

In [26]:
list(ani1x.ds_idx)[:10]

['C1H4N4O4',
 'C1H5N3O5',
 'C2H10N4O3',
 'C2H10N6O1',
 'C2H11N5O1',
 'C2H5N1O5',
 'C3H13N3',
 'C3H2N4O3',
 'C3H4N6O1',
 'C3H6N8O3']

In [27]:
ani1x['C2H5N1O5']

(tensor([-1.7664, -1.1179, -0.0062, -2.2169,  1.0111, -0.2214, -2.3216, -1.9097,
          0.4910, -1.1157, -1.5187, -0.8028, -2.6049,  1.9201, -0.6634,  0.7620,
         -0.1119, -0.3289,  4.2922, -0.2782, -0.4575, -1.2507,  1.0008,  0.6059,
         -2.6771, -0.2026, -0.6266, -1.0518, -0.3457,  0.9245,  1.6454,  0.0059,
         -0.7716,  2.5284, -0.3719,  0.2558,  3.7604,  0.3561,  0.0786,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]),
 tensor([6, 6, 1, 1, 1, 1, 1, 7, 8, 8, 8, 8, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([-509.4100,    0.0000,    0.0000,    0.0000,    0.0000,    0.0000,
            0.0000,    0.0000,    0.0000,    0.0000,  

In [29]:
lg = 0
for mol in ani1x.ds_idx:
    val = ani1x[mol]
    sz = val[0].shape[0]
    if sz > lg:
        lg = sz
print(lg)

ValueError: index can't contain negative values

In [18]:
ani1x['C1H4N4O4']

(tensor([-1.2263,  0.5377,  0.2725,  4.4949,  0.1034, -0.8453,  1.5547,  0.2805,
         -0.1343, -0.3720,  2.2014,  0.3942, -1.1093, -1.3063,  1.3089, -0.2913,
          1.2546,  0.7393, -1.4998, -0.7878,  0.5395, -2.7570, -1.0798,  0.1456,
         -3.1703, -0.1494, -0.5683,  4.1080,  0.3558,  0.0134,  3.1196, -0.6857,
          0.1812,  2.0523, -0.4274, -0.6370, -2.1777,  0.8613, -0.6015]),
 tensor([6, 1, 1, 1, 1, 7, 7, 7, 7, 8, 8, 8, 8]),
 tensor([-559.6797], dtype=torch.float64))