In [1]:
from quantum_dataset import QM7, QM7b, QM7X, QM9, Champs, SuperSet
from quantum_learning import Learn, Selector, ChampSelector
from quantum_model import FFNet
from torch.optim import Adam
from torch.nn import MSELoss, L1Loss

In [ ]:
opt_params = {'lr': 0.001}
model_params = {'D_in': 23*23, 
                'H': 4096, 
                'D_out': 1, 
                'model_name': 'funnel'}
ds_params = {}
crit_params = {'reduction': 'sum'}

Learn(Dataset=QM7, Model=FFNet, Sampler=Selector, Optimizer=Adam, Criterion=L1Loss, 
      batch_size=256, epochs=200, opt_params=opt_params, model_params=model_params, 
      ds_params=ds_params, crit_params=crit_params, save_model=False, load_model=False)

In [ ]:
opt_params = {'lr': 0.001}
model_params = {'D_in': 23*23, 
                'H': 4096, 
                'D_out': 1, 
                'model_name': 'simple'}
ds_params = {}
crit_params = {'reduction': 'sum'}

Learn(Dataset=QM7, Model=FFNet, Sampler=Selector, Optimizer=Adam, Criterion=L1Loss, 
      batch_size=256, epochs=200, opt_params=opt_params, model_params=model_params, 
      ds_params=ds_params, crit_params=crit_params, save_model=False, load_model=False)

In [ ]:
opt_params = {'lr': 0.001}
model_params = {'D_in': 23*23+13, 
                'H': 4096, 
                'D_out': 1, 
                'model_name': 'funnel'}
ds_params = {'target': 'E', 
             'features': ['alpha_p','alpha_s','HOMO_g','HOMO_p','HOMO_z','LUMO_g',
                          'LUMO_p','LUMO_z','IP','EA','E1','Emax','Imax']}
crit_params = {'reduction': 'sum'}

Learn(Dataset=QM7b, Model=FFNet, Sampler=Selector, Optimizer=Adam, Criterion=L1Loss, 
      batch_size=256, epochs=100, opt_params=opt_params, model_params=model_params, 
      ds_params=ds_params, crit_params=crit_params, save_model=False, load_model=False)

In [ ]:
opt_params = {'lr': 0.001}
model_params = {'D_in': 29*29+29+14, 
                'H': 1024, 
                'D_out': 1, 
                'model_name': 'funnel'}
ds_params = {'n': 133885, 
             'features': ['coulomb','mulliken','A','B','C','alpha','homo',
                          'lumo','gap','r2','zpve','H','U0','U','G','Cv'], 
             'target': 'mu',
             'dim': 29,
             'use_pickle': True}
crit_params = {'reduction': 'sum'}

Learn(Dataset=QM9, Model=FFNet, Sampler=Selector, Optimizer=Adam, Criterion=MSELoss,
      batch_size=512, epochs=10, model_params=model_params, ds_params=ds_params, 
      opt_params=opt_params, crit_params=crit_params, save_model=False, load_model=False)

In [ ]:
opt_params = {'lr': 0.001}
model_params = {'D_in': 128+32+64+32+64, 
                'H': 2048, 
                'D_out': 1, 
                'model_name': 'funnel'}
ds_params = {'n': 4658146, 
             'features': False,
             'use_h5': False,  
             'infer': False}
crit_params = {'reduction': 'sum'}
sample_params = {'split': .1, 'subset': False}

Learn(Dataset=Champs, Model=FFNet, Sampler=ChampSelector, Optimizer=Adam, Criterion=L1Loss,
      batch_size=1024, epochs=10, model_params=model_params, ds_params=ds_params, 
      sample_params=sample_params, opt_params=opt_params, crit_params=crit_params, 
      save_model=True, load_model=False)

In [ ]:
model_params = {'D_in': 128+32+64+32+64, 
                'H': 2048, 
                'D_out': 1, 
                'model_name': 'funnel'}
ds_params = {'features': False,
             'use_h5': False,  
             'infer': True}

Learn(Dataset=Champs, Model=FFNet, Sampler=Selector, batch_size=2048, model_params=model_params, 
      ds_params=ds_params, load_model='./models/20201021_2101.pth', adapt=False)

In [7]:
ds_params = {'n': 133885, 
             'features': ['A','B','C','mu','alpha','homo','lumo', 
                          'gap','r2','zpve','U0','U','H','G','Cv'], 
             'target': 'U0',
             'dim': 10,
             'use_pickle': True}

qm9 = QM9(**ds_params)

loading QM9 datadic from a pickled copy...


In [8]:
qm9.datadic[1].xyz

[['C', '-0.0126981359', ' 1.0858041578', ' 0.0080009958', '-0.535689'],
 ['H', ' 0.002150416', '-0.0060313176', ' 0.0019761204', ' 0.133921'],
 ['H', ' 1.0117308433', ' 1.4637511618', ' 0.0002765748', ' 0.133922'],
 ['H', '-0.540815069', ' 1.4475266138', '-0.8766437152', ' 0.133923'],
 ['H', '-0.5238136345', ' 1.4379326443', ' 0.9063972942', ' 0.133923']]

In [9]:
qm9.datadic[1].coulomb

array([[36.858112 , 10.76564  , 10.765889 , 10.765862 , 10.7656765],
       [ 0.9157931,  0.5      ,  1.7943149,  1.7943105,  1.7942797],
       [ 0.9157931,  1.7942735,  0.5      ,  1.7943105,  1.7942797],
       [ 0.9157931,  1.7942735,  1.7943149,  0.5      ,  1.7942797],
       [ 0.9157931,  1.7942735,  1.7943149,  1.7943105,  0.5      ]],
      dtype=float32)

In [10]:
qm9.datadic[1].adjacency

array([[0., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]], dtype=float32)

In [11]:
qm9[1]

(tensor([ 1.5771e+02,  1.5771e+02,  1.5771e+02,  0.0000e+00,  1.3210e+01,
         -3.8770e-01,  1.1710e-01,  5.0480e-01,  3.5364e+01,  4.4749e-02,
         -4.0479e+01, -4.0476e+01, -4.0475e+01, -4.0499e+01,  6.4690e+00]),
 [],
 tensor([-40.4789]))

In [5]:
ds_params = {'features': ['DIP','HLgap','KSE','atC6','atNUM','atPOL','atXYZ','eAT', 
                          'eC','eDFTB+MBD','eEE','eH','eKIN','eKSE','eL','eMBD','eNE', 
                          'eNN','ePBE0','ePBE0+MBD','eTS','eX','eXC','eXX','hCHG', 
                          'hDIP','hRAT','hVDIP','hVOL','mC6','mPOL','mTPOL','pbe0FOR', 
                          'sMIT','sRMSD','totFOR','vDIP','vEQ','vIQ','vTQ','vdwFOR','vdwR'],
             'dim': 200,
             'target': ['atXYZ'],
             'selector': ['i1-c1-opt']}

qm7x = QM7X(**ds_params)

opening...  <HDF5 file "1000.hdf5" (mode r)>
opening...  <HDF5 file "2000.hdf5" (mode r)>
opening...  <HDF5 file "3000.hdf5" (mode r)>
opening...  <HDF5 file "4000.hdf5" (mode r)>
opening...  <HDF5 file "5000.hdf5" (mode r)>
opening...  <HDF5 file "6000.hdf5" (mode r)>
opening...  <HDF5 file "7000.hdf5" (mode r)>
opening...  <HDF5 file "8000.hdf5" (mode r)>
molecular formula (idmol) mapped:  6899
total molecular structures (idconf) mapped:  6899
molecular formula loaded:  6899


In [6]:
qm7x[1]

(tensor([ 6.0000e-06,  1.1648e+01, -2.7750e+02, -1.9515e+01, -1.1031e+01,
         -1.1031e+01, -1.1031e+01,  6.1704e-01,  1.8885e+00,  1.8885e+00,
          1.8885e+00,  4.0704e+00,  4.0705e+00,  4.0705e+00,  6.9626e+00,
          8.2738e+00,  2.9514e+01,  1.3825e+00,  1.3825e+00,  1.3825e+00,
          1.3825e+00,  6.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,
          1.0000e+00,  9.2872e+00,  1.8785e+00,  1.8785e+00,  1.8784e+00,
          1.8785e+00,  8.0000e-06, -4.0000e-06,  1.0000e-06,  1.0804e+00,
         -1.5000e-05, -1.8000e-05, -3.6015e-01,  4.4809e-01,  9.1480e-01,
         -3.6017e-01, -1.0163e+00, -6.9363e-02, -3.6016e-01,  5.6821e-01,
         -8.4543e-01,  1.9314e+01, -8.2019e+00, -8.7933e+01,  8.9546e+02,
         -1.1031e+01,  1.0963e+03, -6.6021e+02,  6.1704e-01, -2.2546e-02,
         -3.2754e+03,  3.6883e+02, -1.1015e+03, -1.1015e+03, -4.3000e-04,
         -1.7845e+02, -1.8665e+02, -4.4847e+01, -1.6644e-01,  4.1610e-02,
          4.1606e-02,  4.1610e-02,  4.

In [ ]:
ds_params = {'features': ['DIP','HLgap','KSE','atC6','atNUM','atPOL','atXYZ', 
            'eC','eDFTB+MBD','eEE','eH','eKIN','eKSE','eL','eMBD','eNE', 
            'eNN','ePBE0','ePBE0+MBD','eTS','eX','eXC','eXX','hCHG', 
            'hDIP','hRAT','hVDIP','hVOL','mC6','mPOL','mTPOL','pbe0FOR', 
            'sMIT','sRMSD','totFOR','vDIP','vEQ','vIQ','vTQ','vdwFOR','vdwR'],
             'dim': 1024,
             'target': ['eAT'],
             'selector': ['i1-c1-opt']}

opt_params = {'lr': 0.001}

model_params = {'D_in': 1024, 
                'H': 2048, 
                'D_out': 1, 
                'model_name': 'funnel'}

crit_params = {'reduction': 'sum'}

sample_params = {'split': .1, 'subset': False}

Learn(Dataset=QM7X, Model=FFNet, Sampler=Selector, Optimizer=Adam, Criterion=L1Loss,
      batch_size=256, epochs=50, model_params=model_params, ds_params=ds_params, 
      sample_params=sample_params, opt_params=opt_params, crit_params=crit_params, 
      save_model=False, load_model=False)
