In [1]:
from quantum_dataset import QM7, QM7b, QM7X, QM9, Champs, SuperSet
from quantum_learning import Learn, Selector, ChampSelector
from quantum_model import FFNet
from torch.optim import Adam
from torch.nn import MSELoss, L1Loss

In [ ]:
opt_params = {'lr': 0.001}
model_params = {'D_in': 23*23, 
                'H': 4096, 
                'D_out': 1, 
                'model_name': 'funnel'}
ds_params = {}
crit_params = {'reduction': 'sum'}

Learn(Dataset=QM7, Model=FFNet, Sampler=Selector, Optimizer=Adam, Criterion=L1Loss, 
      batch_size=256, epochs=200, opt_params=opt_params, model_params=model_params, 
      ds_params=ds_params, crit_params=crit_params, save_model=False, load_model=False)

In [ ]:
opt_params = {'lr': 0.001}
model_params = {'D_in': 23*23, 
                'H': 4096, 
                'D_out': 1, 
                'model_name': 'simple'}
ds_params = {}
crit_params = {'reduction': 'sum'}

Learn(Dataset=QM7, Model=FFNet, Sampler=Selector, Optimizer=Adam, Criterion=L1Loss, 
      batch_size=256, epochs=200, opt_params=opt_params, model_params=model_params, 
      ds_params=ds_params, crit_params=crit_params, save_model=False, load_model=False)

In [ ]:
opt_params = {'lr': 0.001}
model_params = {'D_in': 23*23+13, 
                'H': 4096, 
                'D_out': 1, 
                'model_name': 'funnel'}
ds_params = {'target': 'E', 
             'features': ['alpha_p','alpha_s','HOMO_g','HOMO_p','HOMO_z','LUMO_g',
                          'LUMO_p','LUMO_z','IP','EA','E1','Emax','Imax']}
crit_params = {'reduction': 'sum'}

Learn(Dataset=QM7b, Model=FFNet, Sampler=Selector, Optimizer=Adam, Criterion=L1Loss, 
      batch_size=256, epochs=100, opt_params=opt_params, model_params=model_params, 
      ds_params=ds_params, crit_params=crit_params, save_model=False, load_model=False)

In [ ]:
opt_params = {'lr': 0.001}
model_params = {'D_in': 29*29+29+14, 
                'H': 1024, 
                'D_out': 1, 
                'model_name': 'funnel'}
ds_params = {'n': 133885, 
             'features': ['coulomb','mulliken','A','B','C','alpha','homo',
                          'lumo','gap','r2','zpve','H','U0','U','G','Cv'], 
             'target': 'mu',
             'dim': 29,
             'use_pickle': True}
crit_params = {'reduction': 'sum'}

Learn(Dataset=QM9, Model=FFNet, Sampler=Selector, Optimizer=Adam, Criterion=MSELoss,
      batch_size=512, epochs=10, model_params=model_params, ds_params=ds_params, 
      opt_params=opt_params, crit_params=crit_params, save_model=False, load_model=False)

In [ ]:
opt_params = {'lr': 0.001}
model_params = {'D_in': 128+32+64+32+64, 
                'H': 2048, 
                'D_out': 1, 
                'model_name': 'funnel'}
ds_params = {'n': 4658146, 
             'features': False,
             'use_h5': False,  
             'infer': False}
crit_params = {'reduction': 'sum'}
sample_params = {'split': .1, 'subset': False}

Learn(Dataset=Champs, Model=FFNet, Sampler=ChampSelector, Optimizer=Adam, Criterion=L1Loss,
      batch_size=1024, epochs=10, model_params=model_params, ds_params=ds_params, 
      sample_params=sample_params, opt_params=opt_params, crit_params=crit_params, 
      save_model=True, load_model=False)

In [ ]:
model_params = {'D_in': 128+32+64+32+64, 
                'H': 2048, 
                'D_out': 1, 
                'model_name': 'funnel'}
ds_params = {'features': False,
             'use_h5': False,  
             'infer': True}

Learn(Dataset=Champs, Model=FFNet, Sampler=Selector, batch_size=2048, model_params=model_params, 
      ds_params=ds_params, load_model='./models/20201021_2101.pth', adapt=False)

In [ ]:
ds_params = {'n': 133885, 
             'features': ['coulomb','mulliken','A','B','C','alpha','homo',
                          'lumo','gap','r2','zpve','H','U0','U','G','Cv'], 
             'target': 'mu',
             'dim': 29,
             'use_pickle': True}

sorted(QM9(**ds_params).ds_idx)[:20]

In [2]:
qm7x = QM7X('/home/fltr/QM7X/')

opening...  <HDF5 file "1000.hdf5" (mode r)>
opening...  <HDF5 file "2000.hdf5" (mode r)>
opening...  <HDF5 file "3000.hdf5" (mode r)>
opening...  <HDF5 file "4000.hdf5" (mode r)>
opening...  <HDF5 file "5000.hdf5" (mode r)>
opening...  <HDF5 file "6000.hdf5" (mode r)>
opening...  <HDF5 file "7000.hdf5" (mode r)>
opening...  <HDF5 file "8000.hdf5" (mode r)>
molecular formula (idmol) selected:  6950
total molecular structures (idconf) selected:  41537
molecular formula loaded:  6950


In [11]:
qm7x[1]

[array([6.e-06]),
 array([11.647887]),
 array([-277.49777,  -19.5151 ,  -11.03115,  -11.03102,  -11.03085,
           0.61704,    1.88845,    1.88846,    1.88851,    4.07037,
           4.07047,    4.07051,    6.96265,    8.27375]),
 array([[29.51409 ],
        [ 1.382479],
        [ 1.382523],
        [ 1.382454],
        [ 1.382469]]),
 array([6, 1, 1, 1, 1]),
 array([[9.287211],
        [1.878467],
        [1.87851 ],
        [1.878445],
        [1.878461]]),
 array([[ 8.000000e-06, -4.000000e-06,  1.000000e-06],
        [ 1.080441e+00, -1.500000e-05, -1.800000e-05],
        [-3.601530e-01,  4.480940e-01,  9.148020e-01],
        [-3.601700e-01, -1.016264e+00, -6.936300e-02],
        [-3.601650e-01,  5.682070e-01, -8.454280e-01]]),
 array([19.313757]),
 array([-8.201925]),
 array([-87.933148]),
 array([895.460508]),
 array([-11.03085]),
 array([1096.305188]),
 array([-660.211789]),
 array([0.61704]),
 array([-0.022546]),
 array([-3275.417738]),
 array([368.831933]),
 array([-1101.471

In [ ]:
list(qm7x[2]['Geom-m2-i1-c1-opt'].values())[2][()]

In [ ]:
list(qm7x[2]['Geom-m2-i1-c1-opt'].values())

In [ ]:
mols = QM7X.map_dataset(in_dir='/home/fltr/QM7X/', selector=['opt'])

In [ ]:
sorted(list(map(int, list(mols.keys()))))[:20]


In [ ]:
mols['27']